"""GDELT FIPS 10-4 country codes -> common name.

FIPS 10-4 letterings are non-obvious and easy to get wrong from memory (e.g.
Nigeria is "NI" but Niger is "NG"; Oman is "MU" but Mauritius is "MP"). This
table was built by querying this project's own ingested `story_clusters`
data for the most common `location` string per `country_code`, not
transcribed from a codebook — so it reflects what this database actually
contains.

Used only for a best-effort "does this chat query name a country" heuristic
so RAG retrieval (intelligence/rag.py) can scope results to a country. This
is keyword matching, not NER: ambiguous names (Georgia the country vs. the
US state, Jordan the country vs. a common given name) are a known, accepted
limitation.
"""

import re

FIPS_COUNTRY_NAMES: dict[str, str] = {
    "US": "United States",
    "IN": "India",
    "UK": "United Kingdom",
    "NI": "Nigeria",
    "AS": "Australia",
    "CH": "China",
    "CA": "Canada",
    "IS": "Israel",
    "PK": "Pakistan",
    "RP": "Philippines",
    "SF": "South Africa",
    "FR": "France",
    "JA": "Japan",
    "IR": "Iran",
    "EI": "Ireland",
    "NZ": "New Zealand",
    "RS": "Russia",
    "GM": "Germany",
    "MY": "Malaysia",
    "CE": "Sri Lanka",
    "GR": "Greece",
    "KE": "Kenya",
    "IT": "Italy",
    "CU": "Cuba",
    "KS": "South Korea",
    "BG": "Bangladesh",
    "UP": "Ukraine",
    "ID": "Indonesia",
    "TU": "Turkey",
    "SP": "Spain",
    "EG": "Egypt",
    "GH": "Ghana",
    "SN": "Singapore",
    "MX": "Mexico",
    "VM": "Vietnam",
    "TH": "Thailand",
    "VE": "Venezuela",
    "SZ": "Switzerland",
    "SA": "Saudi Arabia",
    "UG": "Uganda",
    "ZI": "Zimbabwe",
    "TW": "Taiwan",
    "NP": "Nepal",
    "NL": "Netherlands",
    "AE": "United Arab Emirates",
    "SY": "Syria",
    "FJ": "Fiji",
    "BE": "Belgium",
    "MU": "Oman",
    "QA": "Qatar",
    "LE": "Lebanon",
    "BR": "Brazil",
    "AF": "Afghanistan",
    "IZ": "Iraq",
    "BA": "Bahrain",
    "AL": "Albania",
    "HA": "Haiti",
    "MI": "Malawi",
    "AU": "Austria",
    "CI": "Chile",
    "JM": "Jamaica",
    "SO": "Somalia",
    "NO": "Norway",
    "SU": "Sudan",
    "PO": "Portugal",
    "AM": "Armenia",
    "EZ": "Czech Republic",
    "PL": "Poland",
    "SW": "Sweden",
    "RO": "Romania",
    "YM": "Yemen",
    "GY": "Guyana",
    "DA": "Denmark",
    "HK": "Hong Kong",
    "AJ": "Azerbaijan",
    "TZ": "Tanzania",
    "PE": "Peru",
    "JO": "Jordan",
    "CY": "Cyprus",
    "BB": "Barbados",
    "WA": "Namibia",
    "CO": "Colombia",
    "KU": "Kuwait",
    "CG": "Democratic Republic Of The Congo",
    "ML": "Mali",
    "MO": "Morocco",
    "TD": "Trinidad And Tobago",
    "BU": "Bulgaria",
    "BN": "Benin",
    "MT": "Malta",
    "RW": "Rwanda",
    "GG": "Georgia",
    "CB": "Cambodia",
    "PM": "Panama",
    "PP": "Papua New Guinea",
    "GA": "Gambia",
    "AR": "Argentina",
    "SL": "Sierra Leone",
    "ZA": "Zambia",
    "MK": "Macedonia",
    "NG": "Niger",
    "BF": "Bahamas",
    "KZ": "Kazakhstan",
    "BM": "Myanmar",
    "AG": "Algeria",
    "LU": "Luxembourg",
    "OD": "South Sudan",
    "SG": "Senegal",
    "MC": "Macau",
    "CD": "Chad",
    "MA": "Madagascar",
    "LH": "Lithuania",
    "IC": "Iceland",
    "ET": "Ethiopia",
    "DR": "Dominican Republic",
    "WS": "Samoa",
    "BH": "Belize",
    "KN": "North Korea",
    "FI": "Finland",
    "HU": "Hungary",
    "BX": "Brunei",
    "MN": "Monaco",
    "NS": "Suriname",
    "GV": "Guinea",
    "VT": "Vatican City",
    "TS": "Tunisia",
    "KV": "Kosovo",
    "CM": "Cameroon",
    "CF": "Congo",
    "LY": "Libya",
    "EN": "Estonia",
    "ST": "Saint Lucia",
    "GL": "Greenland",
    "BO": "Belarus",
    "AO": "Angola",
    "ES": "El Salvador",
    "BT": "Bhutan",
    "BC": "Botswana",
    "UV": "Burkina Faso",
    "MZ": "Mozambique",
    "LI": "Liberia",
    "CT": "Central African Republic",
    "SE": "Seychelles",
    "EC": "Ecuador",
    "ER": "Eritrea",
    "MV": "Maldives",
    "UZ": "Uzbekistan",
    "VC": "Saint Vincent And The Grenadines",
    "LA": "Laos",
    "RM": "Marshall Islands",
    "IV": "Cote D'ivoire",
    "NU": "Nicaragua",
    "MP": "Mauritius",
    "CS": "Costa Rica",
    "UY": "Uruguay",
    "TN": "Tonga",
    "KR": "Kiribati",
    "TI": "Tajikistan",
    "GT": "Guatemala",
    "BL": "Bolivia",
    "DJ": "Djibouti",
    "RB": "Serbia",
    "RI": "Serbia",
    "LO": "Slovak Republic",
    "GJ": "Grenada",
    "LT": "Lesotho",
    "BP": "Solomon Islands",
    "KG": "Kyrgyzstan",
    "MD": "Moldova",
    "HO": "Honduras",
    "MG": "Mongolia",
    "TO": "Togo",
    "BK": "Bosnia-Herzegovina",
    "AC": "Antigua And Barbuda",
    "TX": "Turkmenistan",
    "TV": "Tuvalu",
    "PA": "Paraguay",
    "LG": "Latvia",
    "MJ": "Montenegro",
    "AN": "Andorra",
    "HR": "Croatia",
}

_NAME_TO_CODE = {name.lower(): code for code, name in FIPS_COUNTRY_NAMES.items()}
# Longest names first so a multi-word name is matched before any shorter
# name it happens to contain as a substring.
_PATTERNS = [
    (name, re.compile(r"\b" + re.escape(name) + r"\b", re.IGNORECASE))
    for name in sorted(_NAME_TO_CODE, key=len, reverse=True)
]


def detect_country_code(text: str) -> str | None:
    """Best-effort: the FIPS country code for the first country name
    mentioned in `text`, or None. Whole-word matched (so "Indiana" does not
    match "India"); not full NER, so rare ambiguous names (e.g. "Jordan" as
    a person's name, "Georgia" the US state) can false-positive.
    """
    for name, pattern in _PATTERNS:
        if pattern.search(text):
            return _NAME_TO_CODE[name]
    return None
